### ISSUE TITLE
您好，请问该代码在windows10可以跑通吗？

### ISSUE THREAD

**Issue by ouyang25** [WenmuZhou/PytorchOCR#100]
我报了如下错误：OSError:[WinError 126]找不到指定的模块。

**Comment by WenmuZhou** [comment]
具体一点

**Comment by ouyang25** [comment]
> 具体一点

非常感谢您的回复
具体情况如下：
C:\Anaconda2\envs\py3\python.exe C:/Users/ouyangjiabin/Desktop/PytorchOCR/tools/det_train.py
Traceback (most recent call last):
  File "C:/Users/ouyangjiabin/Desktop/PytorchOCR/tools/det_train.py", line 25, in <module>
    from torchocr.postprocess import build_post_process
  File "C:\Users\ouyangjiabin\Desktop\PytorchOCR\torchocr\postprocess\__init__.py", line 6, in <module>
    from .DBPostProcess import DBPostProcess
  File "C:\Users\ouyangjiabin\Desktop\PytorchOCR\torchocr\postprocess\DBPostProcess.py", line 4, in <module>
    from shapely.geometry import Polygon
  File "C:\Anaconda2\envs\py3\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "C:\Anaconda2\envs\py3\lib\site-packages\shapely\geometry\base.py", line 18, in <module>
    from shapely.coords import CoordinateSequence
  File "C:\Anaconda2\envs\py3\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "C:\Anaconda2\envs\py3\lib\site-packages\shapely\geos.py", line 145, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "C:\Anaconda2\envs\py3\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

Process finished with exit code 1
我在Windows10环境下，按照requirements安装了所需包，电脑也有gcc/g++和make环境，但是不知道为何报这个错误，希望得到您指点，谢谢！感激不尽！

**Comment by WenmuZhou** [comment]
感觉是shapely没有装对

**Comment by novioleo** [comment]
楼上正解

**Comment by ouyang25** [comment]
谢谢，十分感谢，解决啦，就是这个安装不对。T_T
