### ISSUE TITLE
idcar2015训练时报错expected Tensor as element 0 in argument 0

### ISSUE THREAD

**Issue by solomon-ma** [WenmuZhou/PytorchOCR#134]
训练指令：CUDA_VISIBLE_DEVICES=7 python tools/det_train.py --config config/solomon_train_db_config.py
LOG信息：
训练过程正常，
在执行第一次验证时
2021-01-06 15:01:03,779 - torchocr - INFO - models saved to ./output/DBNet/checkpoint/latest.pth
2021-01-06 15:01:03,779 - torchocr - INFO - start evaluate
  0%|                                                                           | 0/500 [00:00<?, ?it/s]
2021-01-06 15:01:03,937 - torchocr - ERROR - Traceback (most recent call last):
  File "tools/det_train.py", line 250, in train
    eval_dict = evaluate(net, eval_loader, to_use_device, logger, post_process, metric)
  File "tools/det_train.py", line 150, in evaluate
    for batch_data in tqdm(val_loader):
  File "/home/huima/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/home/huima/anaconda3/envs/chineseocr/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/huima/anaconda3/envs/chineseocr/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/huima/anaconda3/envs/chineseocr/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/huima/anaconda3/envs/chineseocr/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/huima/anaconda3/envs/chineseocr/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/huima/anaconda3/envs/chineseocr/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/huima/playground/PytorchOCR/torchocr/datasets/DetCollateFN.py", line 27, in __call__
    data_dict[k] = torch.stack(data_dict[k], 0)
TypeError: expected Tensor as element 0 in argument 0, but got numpy.ndarray

2021-01-06 15:01:04,033 - torchocr - INFO - recall: 0
2021-01-06 15:01:04,033 - torchocr - INFO - precision: 0
2021-01-06 15:01:04,034 - torchocr - INFO - hmean: 0

**Comment by luotianhang** [comment]
怎么解决的

**Comment by solomon-ma** [comment]
@WenmuZhou 麻烦作者帮忙看一下，一直跑不起来

**Comment by novioleo** [comment]
> @WenmuZhou 麻烦作者帮忙看一下，一直跑不起来

你的dataset中的transform里面有没有执行to_tensor

**Comment by novioleo** [comment]
这个是没有to_tensor的报错

**Comment by solomon-ma** [comment]
torchocr/datasets/icdar15/DetDataSet.py文件下JsonDataSet类的init方法中显示应该执行了to_tensor操作

**Comment by novioleo** [comment]
你debug一下，到dataloader的collate_function里面，看下每个instance的类型，这个地方应该是torch tensor，而不是numpy array

**Comment by s1162276945** [comment]
> @WenmuZhou 麻烦作者帮忙看一下，一直跑不起来

我也碰到这个问题了，请问你现在解决了没

**Comment by jeremy520-source** [comment]
> torchocr/datasets/icdar15/DetDataSet.py文件下JsonDataSet类的init方法中显示应该执行了to_tensor操作
请问您解决了么，我也遇到同样问题，非常困扰，若解决可否告知我方法。

**Comment by fanbooo** [comment]
我通过改DetCollectFN解决了：
class DetCollectFN:
    def __init__(self, *args, **kwargs):
        pass

    def __call__(self, batch):
        data_dict = {}
        to_tensor_keys = []
        for sample in batch:
            for k, v in sample.items():
                if k not in data_dict:
                    data_dict[k] = []
                if isinstance(v, (np.ndarray, torch.Tensor, PIL.Image.Image)):
                    if k not in to_tensor_keys:
                        to_tensor_keys.append(k)
                data_dict[k].append(v)
        for k in to_tensor_keys:
            temps = []
            for tmp in data_dict[k]:
                if isinstance(tmp, np.ndarray):
                    tmp = torch.from_numpy(tmp)
                temps.append(tmp)
            data_dict[k] = torch.stack(temps, 0)
        return data_dict

但是在推断的时候有新的报错，我debug了一下应该是test数据集里图片没有resize成1:1的？请问下作者应该怎么改？：
The size of tensor a (48) must match the size of tensor b (47) at non-singleton dimension 3
![image](https://user-images.githubusercontent.com/27717525/111159885-883a1180-85d4-11eb-9a15-95766fdee68f.png)

**Comment by xiakj** [comment]
@solomon-ma 解决了么，怎么搞的？

**Comment by novioleo** [comment]
@Bourne-M 这个问题解决了吗
