### ISSUE TITLE
max() arg is an empty sequence

### ISSUE THREAD

**Issue by zzcqinag** [WenmuZhou/PytorchOCR#138]
在训练识别的时候遇到以下错误，start evaluate,然后就报错了

Traceback (most recent call last):
  File "tools/rec_train.py", line 259, in train
    eval_dict = evaluate(net, eval_loader, loss_func, to_use_device, logger, converter, metric)
  File "tools/rec_train.py", line 157, in evaluate
    for batch_data in tqdm(val_loader):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/std.py", line 1133, in __iter__
    for obj in iterable:
  File "/media/zzc/0336eddf-d97d-4ea2-a393-9862fed6579a1/train/PytorchOCR-master/torchocr/datasets/RecDataSet.py", line 219, in __next__
    return self.pack(batch_data)
  File "/media/zzc/0336eddf-d97d-4ea2-a393-9862fed6579a1/train/PytorchOCR-master/torchocr/datasets/RecDataSet.py", line 163, in pack
    max_img_w = max({m_img.shape[1] for m_img in all_same_height_images})
ValueError: max() arg is an empty sequence

**Comment by novioleo** [comment]
`max_img_w = max({m_img.shape[1] for m_img in all_same_height_images})`
debug到这，然后看看`all_same_height_images ` 里面是否有图片哈~可能是被过滤掉了
@zzcqinag

**Comment by novioleo** [comment]
@zzcqinag 请问解决没有，可以关了么。

**Comment by zzcqinag** [comment]
没有解决呢，还是这个错误



---Original---

**Comment by novioleo** [comment]
@zzcqinag 那你debug了吗？

**Comment by luotianhang** [comment]
数据按照batchsize取整数倍就可以解决
