### ISSUE TITLE
"从百度网盘pytorchocr/det/imagenet下载预训练模型并放于PytorchOCR/weights目录下"

### ISSUE THREAD

**Issue by xiakj** [WenmuZhou/PytorchOCR#154]
这个预训练模型没有找到，能提供下链接吗？

**Comment by xiakj** [comment]
我这边训练ICDAR2015，报的错是这样的：

(qiumin_py3) ps@ps-Super-Server:~/NewDisk1/ocr_workspace/PytorchOCR$ CUDA_VISIBLE_DEVICES=0 python tools/det_train.py --config config/det_train_db_config.py
2021-03-26 10:19:36,436 - torchocr - INFO - {'exp_name': 'DBNet', 'train_options': {'resume_from': '', 'third_party_name': '', 'checkpoint_save_dir': './output/DBNet/checkpoint', 'device': 'cuda:0', 'epochs': 1200, 'fine_tune_stage': ['backbone', 'neck', 'head'], 'print_interval': 1, 'val_interval': 1, 'ckpt_save_type': 'HighestAcc', 'ckpt_save_epoch': 4}, 'SEED': 927, 'optimizer': {'type': 'Adam', 'lr': 0.001, 'weight_decay': 0.0001}, 'model': {'type': 'DetModel', 'backbone': {'type': 'ResNet', 'layers': 18, 'pretrained': False}, 'neck': {'type': 'FPN', 'out_channels': 256}, 'head': {'type': 'DBHead'}, 'in_channels': 3}, 'loss': {'type': 'DBLoss', 'alpha': 1, 'beta': 10}, 'post_process': {'type': 'DBPostProcess', 'thresh': 0.3, 'box_thresh': 0.7, 'unclip_ratio': 1.5}, 'dataset': {'train': {'dataset': {'type': 'JsonDataset', 'file': '/home/ps/NewDisk1/ocr_workspace/PytorchOCR/dataset/ICDAR2015/detection/train.json', 'mean': [0.485, 0.456, 0.406], 'std': [0.229, 0.224, 0.225], 'pre_processes': [{'type': 'IaaAugment', 'args': [{'type': 'Fliplr', 'args': {'p': 0.5}}, {'type': 'Affine', 'args': {'rotate': [-10, 10]}}, {'type': 'Resize', 'args': {'size': [0.5, 3]}}]}, {'type': 'EastRandomCropData', 'args': {'size': [640, 640], 'max_tries': 50, 'keep_ratio': True}}, {'type': 'MakeBorderMap', 'args': {'shrink_ratio': 0.4, 'thresh_min': 0.3, 'thresh_max': 0.7}}, {'type': 'MakeShrinkMap', 'args': {'shrink_ratio': 0.4, 'min_text_size': 8}}], 'filter_keys': ['img_path', 'img_name', 'text_polys', 'texts', 'ignore_tags', 'shape'], 'ignore_tags': ['*', '###'], 'img_mode': 'RGB'}, 'loader': {'type': 'DataLoader', 'batch_size': 8, 'shuffle': True, 'num_workers': 1, 'collate_fn': {'type': ''}}}, 'eval': {'dataset': {'type': 'JsonDataset', 'file': '/home/ps/NewDisk1/ocr_workspace/PytorchOCR/dataset/ICDAR2015/detection/test.json', 'mean': [0.485, 0.456, 0.406], 'std': [0.229, 0.224, 0.225], 'pre_processes': [{'type': 'ResizeShortSize', 'args': {'short_size': 736, 'resize_text_polys': False}}], 'filter_keys': [], 'ignore_tags': ['*', '###'], 'img_mode': 'RGB'}, 'loader': {'type': 'DataLoader', 'batch_size': 1, 'shuffle': False, 'num_workers': 1, 'collate_fn': {'type': 'DetCollectFN'}}}}}
Traceback (most recent call last):
  File "tools/det_train.py", line 334, in <module>
    main()
  File "tools/det_train.py", line 293, in main
    net = build_model(cfg['model'])
  File "/home/ps/NewDisk1/ocr_workspace/PytorchOCR/torchocr/networks/architectures/__init__.py", line 19, in build_model
    arch_model = eval(arch_type)(Dict(copy_config))
  File "/home/ps/NewDisk1/ocr_workspace/PytorchOCR/torchocr/networks/architectures/DetModel.py", line 27, in __init__
    assert neck_type in neck_dict, f'neck.type must in {neck_dict}'
AssertionError: neck.type must in {'DB_fpn': <class 'torchocr.networks.necks.DB_fpn.DB_fpn'>}

**Comment by novioleo** [comment]
请仔细阅读错误信息并自行修改配置

**Comment by xiakj** [comment]
言简意赅

**Comment by WenmuZhou** [comment]
> 这个预训练模型没有找到，能提供下链接吗？

链接: https://pan.baidu.com/s/1uMWys5lQ5ZfhnaOCPBVqZw  密码: i9du

**Comment by xiakj** [comment]
@WenmuZhou thank u
