### ISSUE TITLE
推理时报AssertionError: neck.type must in {'DB_fpn': <class 'torchocr.networks.necks.DB_fpn.DB_fpn'>}错误

### ISSUE THREAD

**Issue by tonytonglt** [WenmuZhou/PytorchOCR#160]
作者你好，我配置好环境并下载预训练模型后，尝试运行det_infer.py对自己的图片的文字进行检测，但报AssertionError，能帮忙看看是什么原因吗？万般感谢~

$ CUDA_VISIBLE_DEVICES=0 python3 tools/det_infer.py --model_path '/home/xxxx/models/PytorchOCR/pytorchocr/det/icdar2015/db_ResNet50_vd_icdar2015withconfig.pth' --img_path '/home/xxxx/workspace/1.jpg'

Traceback (most recent call last):
  File "tools/det_infer.py", line 76, in <module>
    model = DetInfer(args.model_path)
  File "tools/det_infer.py", line 25, in __init__
    self.model = build_model(cfg['model'])
  File "/home/xxxx/workspace/PytorchOCR/torchocr/networks/architectures/__init__.py", line 19, in build_model
    arch_model = eval(arch_type)(Dict(copy_config))
  File "/home/xxxx/workspace/PytorchOCR/torchocr/networks/architectures/DetModel.py", line 27, in __init__
    assert neck_type in neck_dict, f'neck.type must in {neck_dict}'
AssertionError: neck.type must in {'DB_fpn': <class 'torchocr.networks.necks.DB_fpn.DB_fpn'>}

**Comment by novioleo** [comment]
配置文件中neck只能有DB_fpn。
麻烦以后仔细看看报错信息。谢谢。
@tonytonglt
