### ISSUE TITLE
使用det_infer.py 推理时报错 'Tensor' object has no attribute 'astype'

### ISSUE THREAD

**Issue by feiyun1265** [WenmuZhou/PytorchOCR#164]
Traceback (most recent call last):
  File "G:/PytorchOCR-master_v2/tools/det_infer.py", line 80, in <module>
    box_list, score_list = model.predict(img, is_output_polygon=False)
  File "G:/PytorchOCR-master_v2/tools/det_infer_v2.py", line 49, in predict
    box_list, score_list = self.post_proess(out, data['shape'], is_output_polygon=is_output_polygon)
  File "\PytorchOCR-master_v2\torchocr\postprocess\DBPostProcess.py", line 29, in __call__
    is_output_polygon=is_output_polygon)
  File "G:\PytorchOCR-master_v2\torchocr\postprocess\DBPostProcess.py", line 46, in post_p
    _, contours, _ = cv2.findContours((bitmap * 255).astype(np.uint8), cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
AttributeError: 'Tensor' object has no attribute 'astype'

**Comment by novioleo** [comment]
已修复。。拉取最新代码试试。
@feiyun1265

**Comment by feiyun1265** [comment]
> 已修复。。拉取最新代码试试。
> @feiyun1265

好了，多谢支持
