### ISSUE TITLE
训练的时候，在evaluate过程中出现报错的情况: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED 求解

### ISSUE THREAD

**Issue by mrljwlm** [WenmuZhou/PytorchOCR#186]
2021-07-19 18:59:53,159 - train-ocr - ERROR - Traceback (most recent call last):
  File "I:\DeepLearningSystem\pytorch_ocr\rec_train.py", line 301, in train
    eval_dict = evaluate(net, eval_loader, loss_func, to_use_device, logger, converter, metric)
  File "I:\DeepLearningSystem\pytorch_ocr\rec_train.py", line 190, in evaluate
    output = net.forward(batch_data['img'].to(to_use_device))
  File "I:\DeepLearningSystem\pytorch_ocr\torchocr\networks\architectures\RecModel.py", line 41, in forward
    x = self.neck(x)
  File "C:\Program Files\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "I:\DeepLearningSystem\pytorch_ocr\torchocr\networks\necks\RNN.py", line 61, in forward
    x = self.encoder(x)
  File "C:\Program Files\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "I:\DeepLearningSystem\pytorch_ocr\torchocr\networks\necks\RNN.py", line 34, in forward
    x, _ = self.lstm(x)
  File "C:\Program Files\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Program Files\Python\Python38\lib\site-packages\torch\nn\modules\rnn.py", line 581, in forward
    result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

**Comment by novioleo** [comment]
重启电脑 。
