### ISSUE TITLE
Hi！有一些bug不知道怎么引起的。

### ISSUE THREAD

**Issue by wqz960** [WenmuZhou/PytorchOCR#76]
`2020-07-20 01:40:12,632 - torchocr - INFO - Training...
2020-07-20 01:40:12,632 - torchocr - INFO - train dataset has 10000 samples,1250 in dataloader
2020-07-20 01:40:12,632 - torchocr - INFO - eval dataset has 10000 samples,10000 in dataloader
2020-07-20 01:40:12,765 - torchocr - ERROR - Traceback (most recent call last):
  File "tools/det_train.py", line 205, in train
    for i, batch_data in enumerate(train_loader):  # traverse each batch in the epoch
  File "/home/wqzhaha/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/wqzhaha/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/wqzhaha/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/wqzhaha/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/wqzhaha/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/wqzhaha/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wqzhaha/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/wqzhaha/TOSHIBA EXT/ocr/PytorchOCR/torchocr/datasets/DetDataSet.py", line 104, in __getitem__
    im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'`

您可以试着跑一下训练，torch1.0.1 和 torch1.5.0都出现这个问题，数据集试了两个都出现这个问题。

**Comment by wqz960** [comment]
输入图像是NoneType？

**Comment by novioleo** [comment]
没有找到图像。麻烦找下你确认下目录下是否是有图像的

**Comment by wqz960** [comment]
@novioleo 很蠢的问题，解决了 谢谢，请问工程里面有一键检测+识别的脚本吗，我输入一张图片得到位置和位置中的文字？谢谢您。

**Comment by novioleo** [comment]
代码还不完善，你可以参考。 如果实在想用现成的可以考虑easy ocr和chinese ocr------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;wqz960&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月21日(星期二) 中午11:39
收件人:&nbsp;&quot;WenmuZhou/PytorchOCR&quot;<PytorchOCR@noreply.github.com&gt;;
抄送:&nbsp;&quot;Tao Luo&quot;<744351893@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [WenmuZhou/PytorchOCR] Hi！有一些bug不知道怎么引起的。 (#76)

**Comment by cendelian** [comment]
> @novioleo 很蠢的问题，解决了 谢谢，请问工程里面有一键检测+识别的脚本吗，我输入一张图片得到位置和位置中的文字？谢谢您。
请问你是怎么解决的？我也遇到了一样的问题，路径 图片都是OK的，，，，
