### ISSUE TITLE
error: random_crop_data.py  

### ISSUE THREAD

**Issue by mochp** [WenmuZhou/PytorchOCR#98]
*******************
poly [[1533.5558 3912.3967]
 [1289.3611 3954.4272]
 [1296.0596 3993.3525]
 [1540.2543 3951.322 ]]2020-09-23 15:54:25,165 - torchocr - ERROR - Traceback (most recent call last):
  File "tools/det_train.py", line 211, in train
    for i, batch_data in enumerate(train_loader):  # traverse each batch in the epoch
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nlp/lmy/PytorchOCR/torchocr/datasets/DetDataSet.py", line 103, in __getitem__
    data = self.apply_pre_processes(data)
  File "/home/nlp/lmy/PytorchOCR/torchocr/datasets/DetDataSet.py", line 92, in apply_pre_processes
    data = aug(data)
  File "/home/nlp/lmy/PytorchOCR/torchocr/datasets/det_modules/random_crop_data.py", line 54, in __call__
    poly = ((poly - (crop_x, crop_y)) * scale).tolist()
TypeError: unsupported operand type(s) for -: 'list' and 'tuple'

crop_x,crop_y (0, 0)
*******************

**Comment by mochp** [comment]
作者您好,我使用自己构建的数据集训练DB出现以下问题 图片（1600*2400）
1、random_crop_data.py报错
2、crop_x,crop_y 全部为0  
作者能帮我看看哪出问题了没

**Comment by novioleo** [comment]
https://github.com/WenmuZhou/PytorchOCR/blob/4a4f705c663dbc60563f1921b66415a953fbe12d/torchocr/datasets/det_modules/random_crop_data.py#L25
这个地方你写成:`text_polys = np.array(data['text_polys'])` 即可。
